name: wikibus-apis
env_file:
  - local.env
  - .env
services:
  sources:
    type: node:custom
    command: yarn nodemon --delay 1 -w packages -w apis --verbose --ext ts,ttl,js,trig --ignore **/*.spec.ts --ignore **/*.spec-graphs.ts --exec node --inspect=0.0.0.0:34567 -r ts-node/register --inspect apis/sources/index.ts
    port: 34566
    ssl: true
    overrides:
      image: node:14
      ports:
        - '34567:34567'
      environment:
        DEBUG: app,app:*,hydra,hydra:*,fun-ddr:*,hydra-box,hydra-box:*
        CLOUDINARY_BROCHURES_FOLDER: "wikibus test/brochures"
        CLOUDINARY_DEFAULT_TRANSFORMATION: default_downsize
        CLOUDINARY_THUMB_TRANSFORMATION: media_lib_thumb
        NODE_ENV: development
    moreHttpPorts:
      - 34567
  users:
    type: node:custom
    command: node --inspect=0.0.0.0:34667 -r ts-node/register --inspect apis/users/index.ts
    port: 34666
    ssl: true
    moreHttpPorts:
      - 34667
    overrides:
      image: node:14
      ports:
        - '34667:34667'
  bff:
    type: node:custom
    command: node --inspect=0.0.0.0:34767 -r ts-node/register --inspect apis/bff/index.ts
    port: 34766
    ssl: true
    moreHttpPorts:
      - 34767
    overrides:
      image: node:14
      ports:
        - '34767:34767'
      environment:
        PORT: 34766
        DEBUG: app,app:*,hydra,hydra:*,hydra-box,hydra-box:*
  store:
    type: compose
    services:
      image: blankdots/jena-fuseki:fuseki3.13.1
      command: /docker-entrypoint.sh /jena-fuseki/start-fuseki.sh
      environment:
        ADMIN_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      volumes:
        - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
proxy:
  store:
    - wikibus-store.lndo.site:3030
  sources:
    - wikibus-sources.lndo.site:34566
  users:
    - wikibus-users.lndo.site:34666
  bff:
    - wikibus-bff.lndo.site:34766
